# Generated by Django 2.0.8 on 2018-08-14 15:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('sub_title', models.CharField(max_length=64, verbose_name='二级标题')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='详情')),
                ('link', models.CharField(max_length=254, verbose_name='链接')),
                ('image', models.ImageField(upload_to='design/banner/', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Banner_mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('effect', models.CharField(blank=True, max_length=64, null=True, verbose_name='效果')),
                ('delay_time', models.IntegerField(help_text='以秒为单位', verbose_name='延时')),
                ('auto_slide', models.BooleanField(default=True, verbose_name='自动播放')),
                ('hover', models.BooleanField(default=True, verbose_name='循环')),
                ('status', models.BooleanField(default=True, help_text='开启/关闭', verbose_name='状态')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Banner_mode', verbose_name='类型名字'),
        ),
    ]
