# Generated by Django 2.1 on 2018-08-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_description',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='product.Product_description', verbose_name='商品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category_filter',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Filter', verbose_name='过滤标签'),
        ),
        migrations.AlterField(
            model_name='customer_affiliate',
            name='Customer_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Customer_activity', verbose_name='客户足迹'),
        ),
        migrations.AlterField(
            model_name='customer_affiliate',
            name='bank_account_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='银行帐号码'),
        ),
        migrations.AlterField(
            model_name='customer_affiliate',
            name='customer_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Customer_group', verbose_name='客户组'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product_discount', verbose_name='折扣'),
        ),
    ]
