# Generated by Django 2.1 on 2018-08-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180806_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_attribute_value',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Product_attribute_value', verbose_name='属性'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product_description', verbose_name='商品详情'),
        ),
    ]
