# Generated by Django 2.1 on 2018-08-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180806_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.AddField(
            model_name='product_attribute_value',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='商品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_attribute_value',
            name='attribute_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Attribute', verbose_name='属性值'),
        ),
    ]
