# Generated by Django 2.1 on 2018-08-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180806_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_description',
            name='language',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='product.Language', verbose_name='国家/地区-语言'),
            preserve_default=False,
        ),
    ]
