# Generated by Django 2.1 on 2018-08-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180807_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_discount',
            name='price',
            field=models.DecimalField(decimal_places=9, default=0, help_text='默认为0，则表示没有折扣', max_digits=19, verbose_name='价格'),
        ),
    ]
