# Generated by Django 2.1 on 2018-08-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_filter',
            name='text',
            field=models.CharField(default='', max_length=64, verbose_name='过滤关键字 '),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Filter key'),
        ),
    ]
