# Generated by Django 2.1 on 2018-08-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_value',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='product_option',
            name='name',
            field=models.CharField(default=1, max_length=64, verbose_name='型号名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=64, verbose_name='组名'),
        ),
        migrations.AlterField(
            model_name='option_value',
            name='image',
            field=models.ImageField(blank=True, help_text='页面展示图', null=True, upload_to='option/'),
        ),
        migrations.AlterField(
            model_name='option_value',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Option', verbose_name='选项组'),
        ),
    ]
