# Generated by Django 2.1 on 2018-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20180807_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='option/', verbose_name='选项图'),
        ),
    ]
