# Generated by Django 2.1 on 2018-08-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_option_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_related',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='product_related',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='product_related',
            name='related_id',
            field=models.IntegerField(editable=False, verbose_name='关联ID'),
        ),
        migrations.AlterField(
            model_name='product_related',
            name='related_name',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='product.Product', verbose_name='关联商品'),
        ),
    ]
