# Generated by Django 2.1 on 2018-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180807_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': '语言', 'verbose_name_plural': '语言'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '省份直辖区', 'verbose_name_plural': '省份直辖区'},
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Manufacturer/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(default=1, max_length=64, verbose_name='厂家/制造商'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小，则排序越靠前', verbose_name='排序'),
        ),
    ]
