# Generated by Django 2.1 on 2018-08-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20180807_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': '厂家/制造商', 'verbose_name_plural': '厂家/制造商'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='language_id',
        ),
    ]
