# Generated by Django 2.1 on 2018-08-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20180807_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Promotion_Rate',
        ),
    ]
