# Generated by Django 2.1 on 2018-08-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20180809_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', help_text='其他语言可在详情填写', max_length=256, verbose_name='分类名字'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', help_text='其他国家可以在详情选择填写', max_length=256, verbose_name='默认商品名字'),
        ),
    ]
