# Generated by Django 2.1 on 2018-08-09 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180809_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_attribute_value',
            options={'verbose_name': '属性', 'verbose_name_plural': '属性'},
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name': '产品分类', 'verbose_name_plural': '产品分类'},
        ),
        migrations.AlterModelOptions(
            name='product_description',
            options={'verbose_name': '详情', 'verbose_name_plural': '详情'},
        ),
        migrations.AlterModelOptions(
            name='product_discount',
            options={'verbose_name': '商品折扣', 'verbose_name_plural': '商品折扣'},
        ),
        migrations.AlterModelOptions(
            name='product_download',
            options={'verbose_name': '下载商品数据', 'verbose_name_plural': '下载商品数据'},
        ),
        migrations.AlterModelOptions(
            name='product_filter',
            options={'verbose_name': '商品过滤', 'verbose_name_plural': '商品过滤'},
        ),
        migrations.AlterModelOptions(
            name='product_image',
            options={'verbose_name': '商品附属图', 'verbose_name_plural': '商品附属图'},
        ),
        migrations.AlterModelOptions(
            name='product_option',
            options={'verbose_name': '商品选项', 'verbose_name_plural': '商品选项'},
        ),
        migrations.AlterModelOptions(
            name='product_related',
            options={'verbose_name': '相关联商品', 'verbose_name_plural': '相关联商品'},
        ),
        migrations.AlterModelOptions(
            name='product_special',
            options={'verbose_name': '特价', 'verbose_name_plural': '特价'},
        ),
        migrations.AlterField(
            model_name='product_related',
            name='related_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
