# Generated by Django 2.1 on 2018-08-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20180809_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='mask',
        ),
    ]
