# Generated by Django 2.1 on 2018-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_download_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_special',
            name='price',
            field=models.IntegerField(help_text='原价的减去折扣百分比', verbose_name='折扣百分比%'),
        ),
    ]
