# Generated by Django 2.1 on 2018-08-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20180809_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='product_special',
            name='customer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Customer_group', verbose_name='VIP客户群体'),
        ),
    ]
