# Generated by Django 2.1 on 2018-08-10 17:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20180810_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_description',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='商品详情'),
        ),
    ]
