# Generated by Django 2.0.8 on 2018-08-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20180813_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='category_description',
            options={'verbose_name': '分类详情', 'verbose_name_plural': '分类详情'},
        ),
        migrations.AlterModelOptions(
            name='category_filter',
            options={'verbose_name': '分类筛选', 'verbose_name_plural': '分类筛选'},
        ),
    ]
