# Generated by Django 2.0.8 on 2018-08-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('product', '0026_auto_20180814_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='活动价')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sales', verbose_name='活动名称')),
            ],
        ),
    ]
