# Generated by Django 2.0.8 on 2018-08-13 16:26

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('consignee', models.CharField(max_length=16, verbose_name='收件人')),
                ('phone_number', models.CharField(max_length=12, verbose_name='手机号码')),
                ('address', models.CharField(max_length=64, verbose_name='区域地址')),
                ('detailed_address', models.CharField(max_length=128, verbose_name='详细地址')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=64, verbose_name='类型')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Bill/', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='商品名字')),
                ('price', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='金额')),
                ('delete', models.BooleanField(default=False, verbose_name='删除')),
            ],
        ),
        migrations.CreateModel(
            name='Bind_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('real_name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('identity_card', models.CharField(max_length=18, verbose_name='身份证')),
                ('setpay', models.CharField(blank=True, max_length=254, null=True, verbose_name='支付密码')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, verbose_name='来源')),
                ('money', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金额')),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2018, 8, 14, 16, 26, 30, 51442), verbose_name='有效日期')),
                ('user_mode', models.BooleanField(default=False, verbose_name='领取状态')),
                ('serial_number', models.CharField(default='20180813162630790051481', max_length=32, verbose_name='流水号')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='商品名字')),
                ('image', models.ImageField(blank=True, height_field=78, null=True, upload_to='Change/', verbose_name='商品图片', width_field=78)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('return_id', models.CharField(default='20180813162630900517917', max_length=32, verbose_name='退款编号')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='交易金额')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='退款金额')),
                ('status', models.IntegerField(choices=[(1, '退款成功'), (2, '退款失败'), (3, '正在退款'), (4, '退款异常')], default=3, verbose_name='交易状态')),
            ],
        ),
        migrations.CreateModel(
            name='Changing_or_Refunding_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('return_type', models.IntegerField(choices=[(1, '仅退款'), (2, '退货退款')], default=1, verbose_name='退款类型')),
                ('return_cause', models.IntegerField(choices=[(1, '不想要了'), (2, '买错了'), (3, '没收到货'), (4, '与说明不符'), (5, '其他')], default=1, verbose_name='退款原因')),
                ('return_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='退款金额')),
                ('return_explain', models.CharField(max_length=254, verbose_name='退款说明')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_date', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('product_id', models.IntegerField(verbose_name='产品ID')),
                ('name', models.CharField(max_length=256, verbose_name='产品名字')),
                ('image_url', models.CharField(max_length=256, verbose_name='图片链接')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='价格')),
                ('applause_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='好评率')),
                ('month_sales_volume', models.IntegerField(verbose_name='月销量')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评价内容')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('comment_type', models.IntegerField(choices=[(1, '好评'), (2, '中评'), (3, '差评')], verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateTimeField(verbose_name='有效日期')),
                ('price', models.IntegerField(verbose_name='面额')),
                ('condition', models.IntegerField(help_text='满指定金额才能使用', verbose_name='条件金额')),
                ('coupon_no', models.CharField(default='20180813162630900528274', max_length=32, verbose_name='券编号')),
                ('status', models.BooleanField(default=False, verbose_name='使用状态')),
            ],
        ),
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('product_id', models.IntegerField(verbose_name='浏览产品ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='产品名字')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('address_id', models.IntegerField(verbose_name='地址ID')),
                ('logistics_id', models.IntegerField(verbose_name='物流单号')),
                ('order_status', models.IntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收获'), (4, '待评价')], default=1, verbose_name='订单状态')),
                ('detail_schedule', models.IntegerField(choices=[(1, '拍下商品'), (2, '卖家发货'), (3, '确认收货'), (4, '交易完成')], verbose_name='详情进度')),
                ('order_no', models.CharField(default='20180813162630900537164', max_length=32, verbose_name='流水号')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='交易日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='单价')),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('transaction_status', models.IntegerField(choices=[(1, '交易成功'), (2, '交易关闭'), (3, '买家已付款'), (4, '卖家已发货'), (5, '退款'), (6, '退款/退货')], verbose_name='交易状态')),
                ('operation', models.BooleanField(default=False, help_text='删除订单', verbose_name='交易操作')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='用户名')),
                ('real_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=3, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='return_goods_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.ImageField(upload_to='return_goods_images/', verbose_name='上传凭证')),
                ('return_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Changing_or_Refunding_apply', verbose_name='退货申请ID')),
            ],
        ),
    ]
