# Generated by Django 2.0.8 on 2018-08-14 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20180814_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 15, 17, 25, 30, 889705), verbose_name='有效日期'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='serial_number',
            field=models.CharField(default='20180814172530308897448', max_length=32, verbose_name='流水号'),
        ),
        migrations.AlterField(
            model_name='change',
            name='return_id',
            field=models.CharField(default='20180814172530308900342', max_length=32, verbose_name='退款编号'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_no',
            field=models.CharField(default='20180814172530873089086', max_length=32, verbose_name='券编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='20180814172530730891672', max_length=32, verbose_name='流水号'),
        ),
    ]
