# Generated by Django 2.0.8 on 2018-08-14 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_type',
            name='stype',
        ),
        migrations.AddField(
            model_name='sale_type',
            name='sub_title',
            field=models.CharField(default=1, max_length=64, verbose_name='副级标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_type',
            name='title',
            field=models.CharField(default=1, max_length=64, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='image',
            field=models.ImageField(default=1, upload_to='sales/', verbose_name='活动图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='stype',
            field=models.CharField(default=1, max_length=64, verbose_name='活动类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 17, 25, 30, 883263), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='order_no',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='st',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale_type', verbose_name='促销模块'),
        ),
    ]
