# Generated by Django 2.0.8 on 2018-08-14 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180814_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='style',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'last')], default=1, verbose_name='样式'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 17, 57, 19, 91877), verbose_name='结束时间'),
        ),
    ]
