# Generated by Django 2.0.8 on 2018-08-14 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20180814_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='link',
            field=models.CharField(default='', max_length=254, verbose_name='超链接'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 18, 1, 32, 893132), verbose_name='结束时间'),
        ),
    ]
